export interface Shift {
    id: string;
    member_id: string;
    member_site_position_id: string;
    position_id: string;
    site_id: string;
    date: string;
    start_at: string;
    end_at: string;
    regular_minutes: number;
    overtime_minutes: number;
    premium_minutes: number;
    premium_entries_count: number;
    rate_regular: number | null;
    rate_overtime: number | null;
    time_off: boolean;
    time_off_leave_type_id: string | null;
    time_off_length: number | null;
    time_off_paid: boolean;
    shift_id: string | null;
    approved: boolean;
    created_at: string;
    updated_at: string;
    deleted_at: string | null;
    start_at_clock_caller_phone_number: string | null;
    end_at_clock_caller_phone_number: string | null;
    start_at_clock_notes: string | null;
    end_at_clock_notes: string | null;
    has_caller_phone_number: boolean;
    has_notes: boolean;
    notes: string | null;
    length: number;
    overwritten_length_minutes: number | null;
    break_started_at: string | null;
    break_type: string | null;
    approved_suggested_end_at: boolean;
    suggested_end_at: string | null;
    suggested_end_at_confirmed_at: string | null;
    suggested_end_at_justification: string | null;
    unpaid_break: number;
    paid_break: number;
  }